name: 'TiCS Github Action'
author: 'TIOBE'
description: 'Analyze your code quality with TICS Client. Integrated quality gating allows for decorated pull request reviews.'
inputs:
  projectName:
    description: 'Name of the TICS project'
    required: true
  branchName:
    description: 'Name of the branch in TICS'
    required: false
  branchDir:
    description: 'Location of the files to analyze'
    required: false
  calc:
    description: 'Comma-separated list of metrics to be used'
    required: false
  clientToken:
    description: 'A custom client-data token for the purpose of the Client Viewer functionality.'
    required: false
  tmpDir:
    description: 'Location to store debug information'
    required: false
  installTics:
    description: 'Boolean parameter to install TICS command-line tools on a runner before executing the analysis'
    required: false
  ticsConfiguration:
    description: 'A URL pointing to the "cfg" API endpoint of the TICS Viewer. It contains the name of the TICS Analyzer Configuration or "-" in case of the default configuration'
    required: false
branding:
  icon: 'flag'
  color: 'blue'
runs:
  using: 'node12'
  main: 'src/index.js'
