name: 'TiCS Github Action'
author: 'TIOBE'
description: 'Integrates TICS Client analysis to measure your code quality. The incorporated Quality gating feature enables you to analyze and decorate pull requests.'
inputs:
  projectName:
    description: 'Name of the TICS project'
    required: true
  branchName:
    description: 'Name of the branch in TICS'
    required: false
  branchDir:
    description: 'Location of the files to analyze'
    required: false
  calc:
    description: 'Comma-separated list of metrics to be used'
    required: false
  clientToken:
    description: 'A custom client-data token for the purpose of the Client Viewer functionality.'
    required: false
  extendTics:
    description: 'Options to extend TiCS, see the documentation.'
    required: false
  hostnameVerification:
    description: 'Necessary in case of self-signed certificates. [Documentation on Client-side SSL/TLS](https://portal.tiobe.com/2022.2/docs/#doc=admin/admin_11_viewer.html%23ssl-wrapper)'
    required: false
  installTics:
    description: 'Boolean parameter to install TICS command-line tools on a runner before executing the analysis'
    required: false
  logLevel:
    description: 'Show logging of information other than steps taken during the action. Options are `default`, `none` and `debug`'
    required: false
  showAnnotations:
    description: 'Show the latest TiCS annotations directly in the GitHub Pull Request review.'
    required: false
  ticsAuthToken:
    description: 'Authentication token to authorize the plugin when it connects to the TICS Viewer.'
    required: false
  ticsConfiguration:
    description: 'A URL pointing to the "cfg" API endpoint of the TICS Viewer. It contains the name of the TICS Analyzer Configuration or "-" in case of the default configuration'
    required: true
  tmpDir:
    description: 'Location to store debug information.'
    required: false
  viewerUrl:
    description: 'The publicly available Viewer URL of TiCS viewer to link the links in the review to. (e.g. https://domain.com/tiobeweb/TiCS)'
    required: false
branding:
  icon: 'flag'
  color: 'blue'
runs:
  using: 'node16'
  main: 'dist/index.js'
