name: Build
on:
  push:
    branches:
      - main
jobs:
  build:
    name: build
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TIOBE_TOKEN }}
      - run: |
          git config user.name ${{ secrets.TIOBE_NAME }}
          git config user.email ${{ secrets.TIOBE_EMAIL }}
      - name: Build
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: |
          npm ci
          npm run all
      - name: Setup git config
        uses: actions/checkout@v3
      - name: Commit and push
        run: |
          git diff --quiet dist || (git add dist && git commit -m 'Build dist after push to main')
          git push origin main
