name: Integration Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.x
        id: dispatch_client_test
        with:
          route: POST /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches 
          owner: tiobetestlab
          repo: github-action-test
          workflow_id: ticsclient.yml
        env:
          GITHUB_TOKEN: ${{ secrets.TIOBETESTLAB_PAT }}
