name: Integration Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  trigger-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Integration tests
        uses: octokit/request-action@v2.x
        id: dispatch_client_multiproject_test
        with:
          route: POST /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches
          owner: tiobetestlab
          repo: github-action-tests
          workflow_id: integration.yml
          data: '{ "ref": "main" }'
        env:
          GITHUB_TOKEN: ${{ secrets.TIOBETESTLAB_PAT }}
