name: Test

on: push

jobs:
  Jest:
    name: Jest
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'Build dist after push to main') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Jest
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 16
      - run: npm ci
      - run: npm run test-coverage
