name: TICS Client

on: [pull_request]

jobs:
  TICS:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.2
      - run: npm ci
      - name: TICS GitHub Action
        uses: tiobe/tics-github-action@v2
        with:
          projectName: tics-github-action
          ticsConfiguration: https://eboit.tiobe.com/tiobeweb/TICS/api/cfg?name=main
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          ticsAuthToken: ${{ secrets.EBOIT_CLIENT_TOKEN }}
          installTics: true
          postAnnotations: true
